### ISSUE TITLE
Add blacklist region filtering

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/NGI-ChIPseq#31]
It would be nice to bring this workflow and the the `chipseq_qc` pipeline by @orzechoj into line in terms of functionality.

The pipelines are pretty similar, the main thing I can see that's missing here is the `bedtools_intersectNeg` functionality:

> **Bedtools intersectNeg**
> Takes a bam file and a bed file with regions, given by the flag blacklistFile. Filters the bam file, so the only reads not present in the blacklist regions are included in the output. Uses bedtools intesect for this.

Module code is [here](https://github.com/ewels/ClusterFlow/blob/master/modules/bedtools_intersectNeg.cfmod.pl), but it basically comes down to the following command:

```
bedtools intersect -abam $INPUT -b $blacklistFile -v > $OUTPUT
```

The `$blacklistFile` is a new type of reference file that we'll need to add to the config.

@orzechoj - is there anything else that you think we should add? Docs about current output from this pipeline are [here](https://github.com/SciLifeLab/NGI-ChIPseq/blob/master/docs/output.md).

Phil

**Comment by orzechoj** [comment]
Just had a quick look at the pipeline and docs, and it looks good! Besides bedtools_intersectNeg, I think that the main differences are:

1. The other pipeline in clusterflow also produces bigwig coverage tracks using bamCoverage from deepTools.
2. The fragment length calculated on phantompeaktools is actually used in deepTools/bamCoverage, deepTools/bamFingerprint.
3. And I also use the fragment lengths when I run MACS2 (although that's not part of the pipeline).

I'm not sure if it's a lot of work to fix these things, or how urgent they are.

**Comment by ewels** [comment]
URL with common blacklisted regions (could use these as a type of genome reference): https://sites.google.com/site/anshulkundaje/projects/blacklists

**Comment by ewels** [comment]
Done in #49
