### ISSUE TITLE
Strand cross-correlation analysis before, or after de-duplication?

### ISSUE THREAD

**Issue by sifakise** [SciLifeLab/NGI-ChIPseq#40]
According to [this publication](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3989762/):

> _"The evaluation of ChIP quality following duplicate removal may therefore underestimate the extent of ChIP enrichment relative to background..." ... "We recommend the assessment of RSC and NSC prior to blacklisting or duplicate removal..."_

Thus, perhaps, steps `phantompeakqualtools` and `calculateNSCRSC` could be performed on the non-deduplicated data, instead of the deduplicated?

**Comment by ewels** [comment]
Thanks @sifakise! Any thoughts on this @chuan-wang / @orzechoj?

**Comment by chuan-wang** [comment]
Thanks for this info @sifakise! I will look into this.
