### ISSUE TITLE
Add samtools stats for mapping stats

### ISSUE THREAD

**Issue by orzechoj** [SciLifeLab/NGI-ChIPseq#44]
It would be nice to have the mapping stats from BWA in the multiqc report.

**Comment by ewels** [comment]
Agreed! BWA doesn't output any summary statistics, so it's not possible to add it directly to MultiQC. However, we could add a process that runs `samtools stats`, which will give summary statistics to show in the report.

**Comment by ewels** [comment]
Done in #51
