### ISSUE TITLE
Put phantompeaktools results in MultiQC report

### ISSUE THREAD

**Issue by orzechoj** [SciLifeLab/NGI-ChIPseq#45]
It would be nice with a summary of fragment length etc. from phantompeaktools in multiqc too. Ideally the entire plots, but otherwise the fragment lengths and NCS and RCS numbers.

**Comment by ewels** [comment]
Yes, a MultiQC module for this would be nice! Are you volunteering..? ;)

**Comment by orzechoj** [comment]
Why not? I'll put it my list of thing to do.
