### ISSUE TITLE
Remove multimapping reads

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/NGI-ChIPseq#53]
It's generally considered best practice to remove multimapping reads for ChIP-seq analysis (eg. the classic `bowtie -m 1` for bowtie1). Most modern mappers, including `bwa mem` that we use here, don't have an equivalent option. However, `samtools view` can be used to filter out reads with low mapping scores. See biostars posts [here](https://www.biostars.org/p/167892/) and [here](https://www.biostars.org/p/76893/) (and many other places I'm sure).

It would be good to add in an extra filter step like this, possibly making it optional.

**Comment by agata-sm** [comment]
Removing secondary alignments is not removing multimapping reads - their primary alignments are still retained in the bam file (re first link). I only use `bwa` very occasionally, but [this](https://www.biostars.org/p/18128/) is a filtering strategy I would go for. Does the solution have to use `samtools`? I like `ngsutils` for filtering, and there is a module available now at Uppmax. 

For correctness sake (even if it won't be used anyway):
```
bamutils filter $filename $file_uniq -failed $failed_reads -eq XT:A R
```

... it used to be (of course wrong, U should be retained):
```
bamutils filter $filename $file_uniq -failed $failed_reads -eq XT:A U
```

I used this command on output of `bwa aln`. I am not sure if `bwa mem` outputs the `XT:A` flags though, the link above suggests that it does.
One can add additional filter for MAPQ if desired - not sure how much that will change the output, though.

**Comment by ewels** [comment]
As of yesterday, the pipeline doesn't use UPPMAX environment modules any more - instead it uses singularity containers ported from a docker container. This makes the pipeline much more portable and reproducible 🎉 

So yes, we could certainly add `ngstools` if we need it. But it'll make this singularity image larger, so if we can do it with `samtools` then it's probably better to stick with what we already have.

Phil

**Comment by chuan-wang** [comment]
Solved.
