### ISSUE TITLE
deepTools - bamPEFragmentSize, plotPCA

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/NGI-ChIPseq#54]
When running with paired-end input, it could be nice to run deepTools bamPEFragmentSize (and pick this up in the MultiQC report). See http://deeptools.readthedocs.io/en/latest/content/tools/bamPEFragmentSize.html

![dt](http://deeptools.readthedocs.io/en/latest/_images/ExampleFragmentSize.png)

**Comment by ewels** [comment]
Also a PCA plot using `plotPCA` - http://deeptools.readthedocs.io/en/latest/content/tools/plotPCA.html

**Comment by chuan-wang** [comment]
Solved.

**Comment by ewels** [comment]
Not yet solved - still waiting for integration into MultiQC.

**Comment by chuan-wang** [comment]
Aha, sorry.
