### ISSUE TITLE
workflow config not available when parsing config

### ISSUE THREAD

**Issue by ewels** [SciLifeLab/NGI-ChIPseq#59]
Builds have started failing due to the new v0.27 release of nextflow giving hard failures for missing config variables.

This line has never worked: https://github.com/SciLifeLab/NGI-ChIPseq/blob/master/nextflow.config#L16 - `workflow` isn't available yet when parsing the config file. This always returned an empty value before giving `:latest` as expected, so was a silent error.

Now it fails: https://travis-ci.org/SciLifeLab/NGI-ChIPseq/builds/326839056#L648

This is discussed on gitter here: https://gitter.im/nextflow-io/nextflow?at=5a54d682ae53c15903c81509

Maybe squiggly brackets + defining the container tag under the process scope may work...

**Comment by ewels** [comment]
https://gitter.im/nextflow-io/nextflow?at=5a54dab06117191e6144e624

> Paolo Di Tommaso @pditommaso 16:07
> but you should still be able to reduce it to a closure def such as
> ```groovy
> container = { "scilifelab/ngi-chipseq:${workflow.revision ? workflow.revision : 'latest'" }
> ```

**Comment by chuan-wang** [comment]
https://github.com/SciLifeLab/NGI-ChIPseq/pull/60
