### ISSUE TITLE
To high memory requirement for local jobs

### ISSUE THREAD

**Issue by orzechoj** [SciLifeLab/NGI-ChIPseq#61]
The jobs run locally (i.e. on the login node) are get_software_versions and multiqc. These fail when I run them on bianca, where I can only get 7Gb memory on the login node. Currently I use the pipeline with base config file like this:

  $get_software_versions {
    memory = { check_max( 2.GB * task.attempt, 'memory' ) }
    executor = 'local'
    errorStrategy = 'ignore'
  }
  $multiqc {
    memory = { check_max( 2.GB * task.attempt, 'memory' ) }
    executor = 'local'
    errorStrategy = { task.exitStatus == 143 ? 'retry' : 'ignore' }
  }

**Comment by chuan-wang** [comment]
Fixed in PR #63.
