### ISSUE TITLE
Peak annotation requires internet access

### ISSUE THREAD

**Issue by orzechoj** [SciLifeLab/NGI-ChIPseq#62]
There are several commands in post_peak_calling_processing.r that assumes that we have an internet connection. This can sometimes be a problem.

1.) R modules are installed on the fly (lines 17-34)

Could this be solved by putting these modules in the singularity image?

2.) Genome annotation is downloaded from ensembl using biomart (lines 51, 66, 116).

Not sure what's the best solution to this. Maybe use static annotation files? Or make the annotation step optional??

**Comment by ewels** [comment]
1) Yes, this should be the case already but it must be missing. The script only falls back to trying to install the package if something is wrong.

2) We should be able to handle these files in the same way that we handle all other reference files.

**Comment by chuan-wang** [comment]
1. Problem of R package loading has been fixed in PR #63.
2. I haven't found a good way to handle biomart datasets locally. Will work more on it.

**Comment by chuan-wang** [comment]
2. Fixed in PR #64.
